val_dataset4:
  root_path_KernelWarehouse:  ./CDD/motion_again/motion_kernel_warehouse.npz #kernel warehouse #kernel warehouse
  pca_matrix_path: ./depth_pca_15.pth
  dataset:
    name: five-image-folders
    args:
      root_path_HR: ./CDD/motion_again/HR/train
      root_path_LR: ./CDD/motion_again/LR/train/1.0
      root_path_Depth: ./CDD/motion/depth_estimate/train
      root_path_Label: ./CDD/motion/seg_estimate/train
      root_path_Kernel: ./CDD/motion_again/Kernel/train
      first_k: 800
      repeat: 1
      cache: bin
  wrapper:
    name: sr-blur-kernel
    args:
      scale_min: 4.0
      scale_max: 4.0
      augment: false
      test: True
      deg_type: motion
  batch_size: 1
eval_type: div2k-4
data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}
state: stage2_c15
optimizer:
  name: adam
  args:
    lr:  1.e-4  #2.5e-5 #1.e-4
epoch_max: 1000
multi_step_lr:
  milestones: [200, 400, 600, 800]
  gamma: 0.5


train_weight: [1, 0.1, 0.05, 0.01, 0.05, 0.01]
epoch_val: 10
epoch_save: 100
version: ma_train